### signup a user
POST http://localhost:3000/users/sign-up
Content-Type: application/json

{
    "name": "hasan",
    "email": "hasan@gmail.com",
    "password": "secure_pass"
} 

### signin a user
POST http://localhost:3000/users/sign-in
Content-Type: application/json

{
    "name": "hasan",
    "email": "hasan@gmail.com",
    "password": "secure_pass"
} 

### All users
GET http://localhost:3000/users

### A user
GET http://localhost:3000/users/6

### A user by email
GET http://localhost:3000/users?email=aa@gmail.com

### delete a user
DELETE http://localhost:3000/users/2

### update a user
PATCH http://localhost:3000/users/2
Content-Type: application/json

{
    "email": "hasan@gmail.com",
    "password": "hasan",
    "name,": "hasan"
} 

### Me
GET http://localhost:3000/users/me

### Whoami
GET http://localhost:3000/users/whoami

### sign out
POST  http://localhost:3000/users/sign-out

### Test cookie to set - serializer might remove fields so uncomment
GET http://localhost:3000/users/set-cookie/hasan

### Test cookie to get value - serializer might remove fields so uncomment
GET http://localhost:3000/users/get-cookie

### Test cookie to get specific cookie value - serializer might remove fields so uncomment
GET http://localhost:3000/users/get-cookie?value=userId


###